### ISSUE TITLE
UX Overflow content hidden if screen width too narrow

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-securityreport#31]
When opening the security report (through the CMS' Reports navigation) on a window/tab with narrow screen width, the overflow content is hidden and can not be accessed by other means than extending the screen width. 

```
silverstripe/securityreport               dev-master 24a71d6

silverstripe/framework                    4.1.x-dev 9ed3cd4
silverstripe/cms                          4.1.x-dev 7dea009
silverstripe/reports                      4.1.x-dev ac23686
```

Note that in contrast in CWP 1.8.1 a horizontal scroll bar gets added, so the relevant content is still accessible.

**Comment by robbieaverill** [comment]
Ok this looks like an issue for GridField itself, and should be logged on framework. It could perhaps be the same as this issue? https://github.com/silverstripe/silverstripe-framework/issues/3742

I'm going to close this as a duplicate of that for now, since resolving that issue would fix this issue too.

I have reproduced the fact that this is a regression from CWP 1.8, however, and have noted this on that issue.
